# -*- coding: utf-8 -*-
"""生成小程序可 require 的锚点候选数据模块 data/reference_elements.js。

锚点候选 = 信标(ble_deployment.json) + 拓扑节点(geojson topology.nodes)。
两者均使用与 FP 网格一致的绝对坐标系，故相对坐标 = 采集点绝对坐标 - 锚点绝对坐标。

输出：fingerprint-collector/data/reference_elements.js
  module.exports = { venueId, venueName, elements: [ {id,label,type,floor,abs:[x,y]}, ... ] }
  type ∈ 'beacon' | 'topo'
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
BLE = os.path.join(ROOT, "result", "ble_deployment.json")
GEO = os.path.join(ROOT, "result", "school_building_01_map_v9.geojson")
OUT = os.path.join(ROOT, "fingerprint-collector", "data", "reference_elements.js")

MAJOR_TO_FLOOR = {1: 1, 2: 2}


def floor_from_id(eid):
    # 拓扑节点 id 形如 F1-TR-0001 -> 1
    if eid and eid.startswith("F") and "-" in eid:
        try:
            return int(eid[1:].split("-")[0])
        except ValueError:
            return None
    return None


def main():
    ble = json.load(open(BLE, encoding="utf-8"))
    geo = json.load(open(GEO, encoding="utf-8"))
    venue_id = geo.get("venueId")
    venue_name = geo.get("venueName")

    elements = []

    # 信标
    for b in ble.get("beacons", []):
        cid = b.get("beaconId")
        coords = b.get("coordinates")
        if not coords or len(coords) < 2:
            continue
        floor = MAJOR_TO_FLOOR.get(b.get("major"))
        if floor is None:
            floor = floor_from_id(cid)
        elements.append({
            "id": cid,
            "label": "信标 " + str(cid),
            "type": "beacon",
            "floor": floor,
            "abs": [round(float(coords[0]), 3), round(float(coords[1]), 3)],
        })

    # 拓扑节点
    for fk, fv in geo.get("floors", {}).items():
        topo = fv.get("topology", {})
        nodes = topo.get("nodes", [])
        for n in nodes:
            nid = n.get("id")
            coords = n.get("coordinates")
            if not nid or not coords or len(coords) < 2:
                continue
            floor = floor_from_id(nid)
            label = nid
            extra = n.get("label")
            if extra:
                label = f"{nid}（{extra}）"
            elements.append({
                "id": nid,
                "label": label,
                "type": "topo",
                "floor": floor,
                "abs": [round(float(coords[0]), 3), round(float(coords[1]), 3)],
            })

    # 排序：楼层升序、类型、id
    elements.sort(key=lambda e: (e["floor"] or 0, e["type"], e["id"]))

    out = (
        "// AUTO-GENERATED by tools/gen_reference_elements.py\n"
        "// 锚点候选 = 信标(ble_deployment.json) + 拓扑节点(geojson topology.nodes)\n"
        "// 与 FP 网格同一绝对坐标系；相对坐标 = 采集点绝对坐标 - 锚点.abs\n"
        "module.exports = {\n"
        f"  venueId: {json.dumps(venue_id, ensure_ascii=False)},\n"
        f"  venueName: {json.dumps(venue_name, ensure_ascii=False)},\n"
        f"  count: {len(elements)},\n"
        f"  elements: {json.dumps(elements, ensure_ascii=False)}\n"
        "};\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(out)

    n_beacon = sum(1 for e in elements if e["type"] == "beacon")
    n_topo = sum(1 for e in elements if e["type"] == "topo")
    print(f"  锚点候选总数: {len(elements)} (信标 {n_beacon} / 拓扑 {n_topo})")
    print(f"  写入 -> {OUT}")


if __name__ == "__main__":
    main()
